/*

!!GENERATING & USING SEQUENCES - USING AUTO-INCREMENT VALUES TO ASSOCIATE TABLES!!

> You use sequence values from one table as keys in a second table so that you can associate
rows in the two tables with each other. But the associations aren’t being set up properly

> You’re probably not inserting rows in the proper order, or you’re losing track of the
sequence values. 
	>> Change the insertion order, or save the sequence values so that you can refer to 
	them when you need them

*/

/*
> Be careful with an AUTO_INCREMENT value used as an ID value in a master table if you
also store the value in detail table rows for the purpose of linking the detail rows to the
proper master table row

> The RIGHT way is to insert all the information for the first table, then proceed to the next
	>> The WRONG way is to add all the master rows into the table, then add all the detail rows 
	to the table
	
> If the detail table contains its own AUTO_INCREMENT column, you must be even more
careful about how you add rows to the tables

> To avoid difficulty, save the sequence value generated by the insert into the master
table and use the saved value for the inserts into the detail table
*/